theme: jekyll-theme-primer

title: "Omar Hyder"
email: "ohyder[at]mgh[dot]harvard[dot]edu"
description: "Anesthesiologist, Intensivist, Data Enthusiast, Outcomes Researcher"
baseurl: ""
url: "https://ohyder.github.io"

# keep defaults you want
collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
