remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

title: "Omar Hyder"
email: "ohyder[at]mgh[dot]harvard[dot]edu"
description: "Anesthesiologist, Intesnivist, Data Enthusiast, Outcomes Researcher, Bean-to-bar Chocolate Maker"
baseurl: "" # no leading slash for user site
url: "https://ohyder.github.io"

# theme options
theme_skin: "minimal"
show_git_profile: true
collections:
  posts:
    output: true

# navigation (example)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
