remote_theme: "mmistakes/minimal-mistakes"

title: "Omar Hyder"
email: "ohyder[at]mgh[dot]harvard[dot]edu"
description: "Anesthesiologist, Intensivist, Data Enthusiast, Outcomes Researcher, Bean-to-bar Chocolate Maker"
baseurl: "" # no leading slash for user site
url: "https://ohyder.github.io"

# theme options
theme_skin: "minimal"
show_git_profile: true

collections:
  posts:
    output: true

# defaults for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"

